### ISSUE TITLE
Plugin Problem Ros Humble Gazebo Garden

### ISSUE THREAD

**Issue by nadia-97** [osrf/vrx#846]
[Err] [SystemLoader.cc:125] Failed to load system plugin [gz::sim::systems::ForceTorque] : could not instantiate from library [gz-sim-forcetorque-system] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/libignition-gazebo-forcetorque-system.so].

I installed vrx using the humble branch as I am using ros2 humble with gazebo garden and ubuntu 22.04. I am facing an issue with some plug ins, one of them is mentioned above. The simulation launches with the command mentioned below and in the simulation the water is not there and the sky glitches, I am assuming these are due to the important plug ins not being found. 

command: ros2 launch vrx_gz competition.launch.py world:=sydney_regatta

I am pasting the entire log with the errors below:

[INFO] [launch]: All log files can be found below /home/nadia/.ros/log/2025-07-24-17-45-33-257701-nadia-pc-18175
[INFO] [launch]: Default logging verbosity is set to INFO
['xacro', '/home/nadia/vrx_ws/install/share/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro', 'namespace:=wamv', 'locked:=true', 'vrx_sensors_enabled:=true', 'thruster_config:=H']
[INFO] [ign gazebo-1]: process started with pid [18178]
[INFO] [monitor_sim-2]: process started with pid [18180]
[INFO] [create-3]: process started with pid [18183]
[INFO] [parameter_bridge-4]: process started with pid [18185]
[create-3] [INFO] [1753371933.746944988] [ros_gz_sim]: Requesting list of world names.
[parameter_bridge-4] [INFO] [1753371933.761317352] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/clock (ignition.msgs.Clock) -> /clock (rosgraph_msgs/msg/Clock)] (Lazy 0)
[parameter_bridge-4] [INFO] [1753371933.761744027] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/task/info (ignition.msgs.Param) -> /vrx/task/info (ros_gz_interfaces/msg/ParamVec)] (Lazy 0)
[parameter_bridge-4] [INFO] [1753371933.762499013] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/debug/wind/speed (ignition.msgs.Float) -> /vrx/debug/wind/speed (std_msgs/msg/Float32)] (Lazy 0)
[parameter_bridge-4] [INFO] [1753371933.762748027] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/debug/wind/direction (ignition.msgs.Float) -> /vrx/debug/wind/direction (std_msgs/msg/Float32)] (Lazy 0)
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:112:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:105:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/StyleDialog.qml:98:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] qrc:qml/Main.qml:102:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] qrc:/qml/PluginMenu.qml:27:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/Gazebo/GazeboDrawer.qml:242:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[create-3] [INFO] [1753371934.464436503] [ros_gz_sim]: Requested creation of entity.
[create-3] [INFO] [1753371934.464509157] [ros_gz_sim]: OK creation of entity.
[ign gazebo-1] [Dbg] [gz.cc:161] Subscribing to [/gazebo/starting_world].
[ign gazebo-1] [Dbg] [gz.cc:163] Waiting for a world to be set from the GUI...
[ign gazebo-1] [Msg] Received world [sydney_regatta.sdf] from the GUI.
[ign gazebo-1] [Dbg] [gz.cc:167] Unsubscribing from [/gazebo/starting_world].
[ign gazebo-1] [Msg] Ignition Gazebo Server v6.17.0
[ign gazebo-1] [Msg] Loading SDF world file[/home/nadia/vrx_ws/install/share/vrx_gz/worlds/sydney_regatta.sdf].
[ign gazebo-1] [Msg] Serving entity system service on [/entity/system/add]
[ign gazebo-1] [Dbg] [Physics.cc:804] Loaded [ignition::physics::dartsim::Plugin] from library [/usr/lib/x86_64-linux-gnu/ign-physics-5/engine-plugins/libignition-physics-dartsim-plugin.so]
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::Physics] for entity [1]
[ign gazebo-1] [Msg] Create service on [/world/sydney_regatta/create]
[ign gazebo-1] [Msg] Remove service on [/world/sydney_regatta/remove]
[ign gazebo-1] [Msg] Pose service on [/world/sydney_regatta/set_pose]
[ign gazebo-1] [Msg] Pose service on [/world/sydney_regatta/set_pose_vector]
[ign gazebo-1] [Msg] Light configuration service on [/world/sydney_regatta/light_config]
[ign gazebo-1] [Msg] Physics service on [/world/sydney_regatta/set_physics]
[ign gazebo-1] [Msg] SphericalCoordinates service on [/world/sydney_regatta/set_spherical_coordinates]
[ign gazebo-1] [Msg] Enable collision service on [/world/sydney_regatta/enable_collision]
[ign gazebo-1] [Msg] Disable collision service on [/world/sydney_regatta/disable_collision]
[ign gazebo-1] [Msg] Material service on [/world/sydney_regatta/visual_config]
[ign gazebo-1] [Msg] Material service on [/world/sydney_regatta/wheel_slip]
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[ign gazebo-1] [Dbg] [Sensors.cc:506] Configuring Sensors system
[ign gazebo-1] [Dbg] [Sensors.cc:431] SensorsPrivate::Run
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::Sensors] for entity [1]
[ign gazebo-1] [Dbg] [Sensors.cc:411] SensorsPrivate::RenderThread started
[ign gazebo-1] [Dbg] [Sensors.cc:258] Waiting for init
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::Imu] for entity [1]
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::Magnetometer] for entity [1]
[ign gazebo-1] [ignition::plugin::Loader::LookupPlugin] Failed to get info for [gz::sim::systems::ForceTorque]. Could not find a plugin with that name or alias.
[ign gazebo-1] [Err] [SystemLoader.cc:125] Failed to load system plugin [gz::sim::systems::ForceTorque] : could not instantiate from library [gz-sim-forcetorque-system] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/libignition-gazebo-forcetorque-system.so].
[ign gazebo-1] [ignition::plugin::Loader::LookupPlugin] Failed to get info for [gz::sim::systems::ParticleEmitter2]. Could not find a plugin with that name or alias.
[ign gazebo-1] [Err] [SystemLoader.cc:125] Failed to load system plugin [gz::sim::systems::ParticleEmitter2] : could not instantiate from library [gz-sim-particle-emitter2-system] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/libignition-gazebo-particle-emitter2-system.so].
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[ign gazebo-1] [Dbg] [SystemManager.cc:73] Loaded system [gz::sim::systems::Contact] for entity [1]
[ign gazebo-1] [ignition::plugin::Loader::LookupPlugin] Failed to get info for [gz::sim::systems::NavSat]. Could not find a plugin with that name or alias.
[ign gazebo-1] [Err] [SystemLoader.cc:125] Failed to load system plugin [gz::sim::systems::NavSat] : could not instantiate from library [gz-sim-navsat-system] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/libignition-gazebo-navsat-system.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libUSVWind.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libUSVWind.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libUSVWind.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPublisherPlugin.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPublisherPlugin.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPublisherPlugin.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libWaveVisual.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libWaveVisual.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libWaveVisual.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [Err] [SystemLoader.cc:103] Failed to load system plugin [libPolyhedraBuoyancyDrag.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libPolyhedraBuoyancyDrag.so].
[INFO] [create-3]: process has finished cleanly [pid 18183]
[INFO] [optical_frame_publisher-5]: process started with pid [18310]
[INFO] [optical_frame_publisher-6]: process started with pid [18312]
[INFO] [optical_frame_publisher-7]: process started with pid [18314]
[INFO] [parameter_bridge-8]: process started with pid [18319]
[INFO] [pose_tf_broadcaster-9]: process started with pid [18321]
[INFO] [robot_state_publisher-10]: process started with pid [18323]
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:57:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[parameter_bridge-8] [INFO] [1753371934.659533291] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/model/wamv/pose (ignition.msgs.Pose_V) -> /model/wamv/pose (tf2_msgs/msg/TFMessage)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.660532756] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/model/wamv/pose_static (ignition.msgs.Pose_V) -> /model/wamv/pose_static (tf2_msgs/msg/TFMessage)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.660790173] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/joint_state (ignition.msgs.Model) -> /world/sydney_regatta/model/wamv/joint_state (sensor_msgs/msg/JointState)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.661490636] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/vrx/contacts (ignition.msgs.Contacts) -> /vrx/contacts (ros_gz_interfaces/msg/Contacts)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.662234365] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.662528962] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_left_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.662874354] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.663108709] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/front_right_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.663346704] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan (ignition.msgs.LaserScan) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan (sensor_msgs/msg/LaserScan)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.663648272] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan/points (ignition.msgs.PointCloudPacked) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/lidar_wamv_sensor/scan/points (sensor_msgs/msg/PointCloud2)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.664006099] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/image (ignition.msgs.Image) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/image (sensor_msgs/msg/Image)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.664246287] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/camera_info (ignition.msgs.CameraInfo) -> /world/sydney_regatta/model/wamv/link/wamv/base_link/sensor/middle_right_camera_sensor/camera_info (sensor_msgs/msg/CameraInfo)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.664475159] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/gps_wamv_link/sensor/navsat/navsat (ignition.msgs.NavSat) -> /world/sydney_regatta/model/wamv/link/wamv/gps_wamv_link/sensor/navsat/navsat (sensor_msgs/msg/NavSatFix)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.664990557] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [/world/sydney_regatta/model/wamv/link/wamv/imu_wamv_link/sensor/imu_wamv_sensor/imu (ignition.msgs.IMU) -> /world/sydney_regatta/model/wamv/link/wamv/imu_wamv_link/sensor/imu_wamv_sensor/imu (sensor_msgs/msg/Imu)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.665464198] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/left/thrust (std_msgs/msg/Float64) -> wamv/thrusters/left/thrust (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.665942605] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/left/pos (std_msgs/msg/Float64) -> wamv/thrusters/left/pos (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.666394083] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/right/thrust (std_msgs/msg/Float64) -> wamv/thrusters/right/thrust (ignition.msgs.Double)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.666795594] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [wamv/thrusters/right/pos (std_msgs/msg/Float64) -> wamv/thrusters/right/pos (ignition.msgs.Double)] (Lazy 0)
[robot_state_publisher-10] [WARN] [1753371934.666939279] [kdl_parser]: The root link wamv/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-10] [INFO] [1753371934.667138911] [wamv.robot_state_publisher]: got segment wamv/ball_shooter_base_link
[robot_state_publisher-10] [INFO] [1753371934.667211231] [wamv.robot_state_publisher]: got segment wamv/ball_shooter_launcher_link
[robot_state_publisher-10] [INFO] [1753371934.667220985] [wamv.robot_state_publisher]: got segment wamv/base_link
[robot_state_publisher-10] [INFO] [1753371934.667227810] [wamv.robot_state_publisher]: got segment wamv/cpu_cases_link
[robot_state_publisher-10] [INFO] [1753371934.667249332] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_link
[robot_state_publisher-10] [INFO] [1753371934.667255990] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_link_optical
[robot_state_publisher-10] [INFO] [1753371934.667258451] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1753371934.667260704] [wamv.robot_state_publisher]: got segment wamv/front_left_camera_post_link
[parameter_bridge-8] [INFO] [1753371934.667217116] [wamv.ros_gz_bridge]: Creating GZ->ROS Bridge: [wamv/sensors/acoustics/receiver/range_bearing (ignition.msgs.Param) -> wamv/sensors/acoustics/receiver/range_bearing (ros_gz_interfaces/msg/ParamVec)] (Lazy 0)
[robot_state_publisher-10] [INFO] [1753371934.667262764] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_link
[robot_state_publisher-10] [INFO] [1753371934.667265033] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_link_optical
[robot_state_publisher-10] [INFO] [1753371934.667267140] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1753371934.667269195] [wamv.robot_state_publisher]: got segment wamv/front_right_camera_post_link
[robot_state_publisher-10] [INFO] [1753371934.667271158] [wamv.robot_state_publisher]: got segment wamv/gps_wamv_link
[robot_state_publisher-10] [INFO] [1753371934.667273269] [wamv.robot_state_publisher]: got segment wamv/imu_wamv_link
[robot_state_publisher-10] [INFO] [1753371934.667275273] [wamv.robot_state_publisher]: got segment wamv/left_battery_link
[robot_state_publisher-10] [INFO] [1753371934.667277335] [wamv.robot_state_publisher]: got segment wamv/left_engine_link
[robot_state_publisher-10] [INFO] [1753371934.667279294] [wamv.robot_state_publisher]: got segment wamv/left_propeller_link
[robot_state_publisher-10] [INFO] [1753371934.667281399] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_link
[robot_state_publisher-10] [INFO] [1753371934.667283513] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_post_arm_link
[robot_state_publisher-10] [INFO] [1753371934.667285634] [wamv.robot_state_publisher]: got segment wamv/lidar_wamv_post_link
[robot_state_publisher-10] [INFO] [1753371934.667287552] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_link
[robot_state_publisher-10] [INFO] [1753371934.667289497] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_link_optical
[robot_state_publisher-10] [INFO] [1753371934.667291494] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_post_arm_link
[robot_state_publisher-10] [INFO] [1753371934.667293475] [wamv.robot_state_publisher]: got segment wamv/middle_right_camera_post_link
[robot_state_publisher-10] [INFO] [1753371934.667295461] [wamv.robot_state_publisher]: got segment wamv/receiver
[robot_state_publisher-10] [INFO] [1753371934.667297565] [wamv.robot_state_publisher]: got segment wamv/right_battery_link
[robot_state_publisher-10] [INFO] [1753371934.667299541] [wamv.robot_state_publisher]: got segment wamv/right_engine_link
[robot_state_publisher-10] [INFO] [1753371934.667301439] [wamv.robot_state_publisher]: got segment wamv/right_propeller_link
[parameter_bridge-8] [INFO] [1753371934.667781068] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [/pinger/set_pinger_position (geometry_msgs/msg/Vector3) -> /pinger/set_pinger_position (ignition.msgs.Vector3d)] (Lazy 0)
[parameter_bridge-8] [INFO] [1753371934.668396617] [wamv.ros_gz_bridge]: Creating ROS->GZ Bridge: [/wamv/shooters/ball_shooter/fire (std_msgs/msg/Bool) -> /wamv/shooters/ball_shooter/fire (ignition.msgs.Boolean)] (Lazy 0)
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [Msg] Ignition Gazebo GUI    v6.17.0
[ign gazebo-1] [Dbg] [Gui.cc:253] Waiting for subscribers to [/gazebo/starting_world]...
[ign gazebo-1] [Dbg] [Application.cc:92] Initializing application.
[ign gazebo-1] [GUI] [Dbg] [Application.cc:555] Create main window
[ign gazebo-1] [GUI] [Dbg] [PathManager.cc:66] Requesting resource paths through [/gazebo/resource_paths/get]
[ign gazebo-1] [GUI] [Dbg] [Gui.cc:333] GUI requesting list of world names. The server may be busy downloading resources. Please be patient.
[ign gazebo-1] [GUI] [Dbg] [PathManager.cc:55] Received resource paths.
[ign gazebo-1] [GUI] [Dbg] [Gui.cc:391] Requesting GUI from [/world/sydney_regatta/gui/info]...
[ign gazebo-1] [GUI] [Dbg] [GuiRunner.cc:145] Requesting initial state from [/world/sydney_regatta/state]...
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [MinimalScene]
[ign gazebo-1] [GUI] [Msg] Added plugin [3D Scene] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [MinimalScene] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libMinimalScene.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [EntityContextMenuPlugin]
[ign gazebo-1] [GUI] [Msg] Added plugin [Entity Context Menu] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [EntityContextMenuPlugin] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libEntityContextMenuPlugin.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [GzSceneManager]
[ign gazebo-1] [GUI] [Msg] Added plugin [Scene Manager] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [GzSceneManager] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libGzSceneManager.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [InteractiveViewControl]
[ign gazebo-1] [GUI] [Msg] Camera view controller topic advertised on [/gui/camera/view_control]
[ign gazebo-1] [GUI] [Msg] Camera reference visual topic advertised on [/gui/camera/view_control/reference_visual]
[ign gazebo-1] [GUI] [Msg] Camera view control sensitivity advertised on [/gui/camera/view_control/sensitivity]
[ign gazebo-1] [GUI] [Msg] Added plugin [Interactive view control] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [InteractiveViewControl] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libInteractiveViewControl.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [CameraTracking]
[ign gazebo-1] [GUI] [Msg] Added plugin [Camera tracking] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [CameraTracking] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libCameraTracking.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [MarkerManager]
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/Spawn/Spawn.qml:32:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/WorldControl/WorldControl.qml:30:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Msg] Listening to stats on [/world/sydney_regatta/stats]
[ign gazebo-1] [GUI] [Msg] Added plugin [Marker Manager] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [MarkerManager] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libMarkerManager.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [SelectEntities]
[ign gazebo-1] [GUI] [Msg] Added plugin [Select entities] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [SelectEntities] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libSelectEntities.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [VisualizationCapabilities]
[ign gazebo-1] [GUI] [Msg] View as transparent service on [/gui/view/transparent]
[ign gazebo-1] [GUI] [Msg] View as wireframes service on [/gui/view/wireframes]
[ign gazebo-1] [GUI] [Msg] View center of mass service on [/gui/view/com]
[ign gazebo-1] [GUI] [Msg] View inertia service on [/gui/view/inertia]
[ign gazebo-1] [GUI] [Msg] View collisions service on [/gui/view/collisions]
[ign gazebo-1] [GUI] [Msg] View joints service on [/gui/view/joints]
[ign gazebo-1] [GUI] [Msg] View frames service on [/gui/view/frames]
[ign gazebo-1] [GUI] [Msg] Added plugin [Visualization capabilities] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [VisualizationCapabilities] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libVisualizationCapabilities.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [Spawn]
[ign gazebo-1] [GUI] [Msg] Added plugin [Spawn] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [Spawn] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libSpawn.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [WorldControl]
[ign gazebo-1] [GUI] [Msg] Using world control service [/world/sydney_regatta/control]
[ign gazebo-1] [GUI] [Msg] Listening to stats on [/world/sydney_regatta/stats]
[ign gazebo-1] [GUI] [Dbg] [WorldControl.cc:246] Using an event to share WorldControl msgs with the server
[ign gazebo-1] [GUI] [Msg] Added plugin [World control] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [WorldControl] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libWorldControl.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [WorldStats]
[ign gazebo-1] [GUI] [Msg] Listening to stats on [/world/sydney_regatta/stats]
[ign gazebo-1] [GUI] [Msg] Added plugin [World stats] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [WorldStats] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libWorldStats.so]
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/TransformControl/TransformControl.qml:104:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/TransformControl/TransformControl.qml:99:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/TransformControl/TransformControl.qml:94:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/TransformControl/TransformControl.qml:89:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityTree/EntityTree.qml:148:7: QML ToolButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [Shapes]
[ign gazebo-1] [GUI] [Msg] Added plugin [Shapes] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [Shapes] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libShapes.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [Lights]
[ign gazebo-1] [GUI] [Msg] Added plugin [Lights] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [Lights] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libLights.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [TransformControl]
[ign gazebo-1] [GUI] [Dbg] [TransformControl.cc:222] Legacy mode is disabled; this plugin must be used with MinimalScene.
[ign gazebo-1] [GUI] [Msg] Added plugin [Transform control] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [TransformControl] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libTransformControl.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [Screenshot]
[ign gazebo-1] [GUI] [Msg] Screenshot service on [/gui/screenshot]
[ign gazebo-1] [GUI] [Msg] Added plugin [Screenshot] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [Screenshot] from path [/usr/lib/x86_64-linux-gnu/ign-gui-6/plugins/libScreenshot.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [VideoRecorder]
[ign gazebo-1] [GUI] [Dbg] [VideoRecorder.cc:359] Legacy mode is disabled; this plugin must be used with MinimalScene.
[ign gazebo-1] [GUI] [Msg] Added plugin [Video recorder] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [VideoRecorder] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libVideoRecorder.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [ComponentInspector]
[ign gazebo-1] [GUI] [Msg] Added plugin [Component inspector] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [ComponentInspector] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libComponentInspector.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [EntityTree]
[ign gazebo-1] [GUI] [Msg] Added plugin [Entity tree] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [EntityTree] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libEntityTree.so]
[ign gazebo-1] [GUI] [Dbg] [Application.cc:426] Loading plugin [ViewAngle]
[ign gazebo-1] Service [] is not valid.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/ViewAngle/ViewAngle.qml:251:5: Unable to assign int to QColor
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/ViewAngle/ViewAngle.qml:279:5: Unable to assign int to QColor
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/ViewAngle/ViewAngle.qml:333:5: Unable to assign int to QColor
[ign gazebo-1] [GUI] [Wrn] [Component.hh:189] Trying to deserialize component with data type [N3sdf3v125WorldE], which doesn't have `operator>>`. Component will not be deserialized.
[ign gazebo-1] [GUI] [Msg] Move to model service on [/gui/move_to/model]
[ign gazebo-1] [GUI] [Msg] Added plugin [View Angle] to main window
[ign gazebo-1] [GUI] [Msg] Loaded plugin [ViewAngle] from path [/usr/lib/x86_64-linux-gnu/ign-gazebo-6/plugins/gui/libViewAngle.so]
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libWaveVisual.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [GUI] [Err] [SystemLoader.cc:103] Failed to load system plugin [libWaveVisual.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libWaveVisual.so].
[ign gazebo-1] Library [/home/nadia/vrx_ws/install/lib/libWaveVisual.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.
[ign gazebo-1] [GUI] [Err] [SystemLoader.cc:103] Failed to load system plugin [libWaveVisual.so] : couldn't load library on path [/home/nadia/vrx_ws/install/lib/libWaveVisual.so].
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityTree/EntityTree.qml:148:7: QML ToolButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/WorldStats/WorldStats.qml:53:3: QML RowLayout: Binding loop detected for property "x"
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:52:3: QML RenderWindowOverlay: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:797] [QT] file::/EntityContextMenuPlugin/EntityContextMenuPlugin.qml:67:3: QML EntityContextMenu: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [Wrn] [Model.hh:69] Skipping serialization / deserialization for models with //pose/@relative_to attribute.
[ign gazebo-1] [Wrn] [Component.hh:144] Trying to serialize component with data type [N3sdf3v125WorldE], which doesn't have `operator<<`. Component will not be serialized.
[ign gazebo-1] libEGL warning: egl: failed to create dri2 screen
[ign gazebo-1] libEGL warning: egl: failed to create dri2 screen
[INFO] [monitor_sim-2]: process has finished cleanly [pid 18180]
[INFO] [robot_state_publisher-10]: sending signal 'SIGINT' to process[robot_state_publisher-10]
[INFO] [pose_tf_broadcaster-9]: sending signal 'SIGINT' to process[pose_tf_broadcaster-9]
[INFO] [parameter_bridge-8]: sending signal 'SIGINT' to process[parameter_bridge-8]
[INFO] [optical_frame_publisher-7]: sending signal 'SIGINT' to process[optical_frame_publisher-7]
[INFO] [optical_frame_publisher-6]: sending signal 'SIGINT' to process[optical_frame_publisher-6]
[INFO] [optical_frame_publisher-5]: sending signal 'SIGINT' to process[optical_frame_publisher-5]
[INFO] [parameter_bridge-4]: sending signal 'SIGINT' to process[parameter_bridge-4]
[INFO] [ign gazebo-1]: sending signal 'SIGINT' to process[ign gazebo-1]
[robot_state_publisher-10] [INFO] [1753371944.764301959] [rclcpp]: signal_handler(signum=2)
[pose_tf_broadcaster-9] [INFO] [1753371944.765706772] [rclcpp]: signal_handler(signum=2)
[parameter_bridge-8] [INFO] [1753371944.766745351] [rclcpp]: signal_handler(signum=2)
[optical_frame_publisher-7] [INFO] [1753371944.767515956] [rclcpp]: signal_handler(signum=2)
[optical_frame_publisher-6] [INFO] [1753371944.768413862] [rclcpp]: signal_handler(signum=2)
[optical_frame_publisher-5] [INFO] [1753371944.769385813] [rclcpp]: signal_handler(signum=2)
[parameter_bridge-4] [INFO] [1753371944.770138882] [rclcpp]: signal_handler(signum=2)
[INFO] [robot_state_publisher-10]: process has finished cleanly [pid 18323]
[INFO] [pose_tf_broadcaster-9]: process has finished cleanly [pid 18321]
[INFO] [optical_frame_publisher-7]: process has finished cleanly [pid 18314]
[INFO] [parameter_bridge-8]: process has finished cleanly [pid 18319]
[INFO] [optical_frame_publisher-6]: process has finished cleanly [pid 18312]
[INFO] [optical_frame_publisher-5]: process has finished cleanly [pid 18310]
[INFO] [parameter_bridge-4]: process has finished cleanly [pid 18185]
[ERROR] [ign gazebo-1]: process[ign gazebo-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ign gazebo-1]: sending signal 'SIGTERM' to process[ign gazebo-1]
[ERROR] [ign gazebo-1]: process has died [pid 18178, exit code -15, cmd 'ruby /usr/bin/ign gazebo -v 4 -r  sydney_regatta.sdf --force-version 6'].
[INFO] [launch]: process[ign gazebo-1] was required: shutting down launched system

**Comment by caguero** [comment]
Please, take a look at the updated instructions. VRX now [requires](https://github.com/osrf/vrx/wiki/system_requirements) ROS 2 Jazzy, Gazebo Harmonic, and Ubuntu 24.04. Alternatively, you could use the `humble` branch that should work with Gazebo Garden.

**Comment by nadia-97** [comment]
> Please, take a look at the updated instructions. VRX now [requires](https://github.com/osrf/vrx/wiki/system_requirements) ROS 2 Jazzy, Gazebo Harmonic, and Ubuntu 24.04. Alternatively, you could use the `humble` branch that should work with Gazebo Garden.

I did use the humble branch. And upon your suggestion I now tried with ubuntu 24 with ros2 jazzy and gazebo harmonic but I am getting the following error upon launching with the same command. 

ros2 launch vrx_gz competition.launch.py world:=sydney_regatta

[INFO] [launch]: All log files can be found below /home/nadia/.ros/log/2025-07-25-11-58-08-985843-nadia-pc-30036
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
 - ImportError: /usr/lib/python3/dist-packages/sdformat14.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZNK3sdf3v144Cone14AxisAlignedBoxEv
 - InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown

**Comment by caguero** [comment]
We just released 3.0.4 of VRX with the patch to fix the issue. Are you using that version?

**Comment by tuupsuu** [comment]
Im having a similiar problem, where gazebo/vrx gets stuck on:
`[create-3] [INFO] [1754485919.220183507] [ros_gz_sim]: Requesting list of world names.`
if i try to change the include uri in `sydney_regatta.sdf` or try to use another world like `world:=nbpark`.

Im using ros2 jazzy and gazebo harmonic with ubuntu 24 which i got from latest tutorial in the wiki

**Comment by dh392** [comment]
> Please, take a look at the updated instructions. VRX now [requires](https://github.com/osrf/vrx/wiki/system_requirements) ROS 2 Jazzy, Gazebo Harmonic, and Ubuntu 24.04. Alternatively, you could use the `humble` branch that should work with Gazebo Garden.
I have tried the ‘humble’ branch with Ubuntu 22.04, ROS 2 Humble, and Gazebo Garden (version 7). However, I still encounter the above errors, which seem to be due to a conflict with Gazebo version 6. Is there any way to resolve this? Thank you!

**Comment by caguero** [comment]
Closing this one but let us know if you run into any issues using the current VRX version.
